// apps/landing-pages/yarn-chaos/src/components/Hero.tsx
import React from 'react';

const Hero: React.FC = () => {
  return (
    <div className="px-4 py-6 md:px-10 lg:px-20 lg:py-10">
      <div className="mx-auto max-w-7xl">
        <div
          className="relative overflow-hidden rounded-xl bg-cover bg-center min-h-[500px] lg:min-h-[600px] flex flex-col justify-end p-8 md:p-12 lg:p-16 group"
          style={{
            backgroundImage:
              'linear-gradient(rgba(0, 0, 0, 0.2) 0%, rgba(0, 0, 0, 0.5) 100%), url("https://lh3.googleusercontent.com/aida-public/AB6AXuCONh1mvtvCSEBSz56AffdFubXClmQDetPB-Lrl78ukoCVynKaiyW-wuCuwungoYAoR2jYf2zZHgk5UFV_cwK4KVRvMD_E_jgG2HiIHT2oXREJhUHUOiaKdcw-vwzbpWVa_7KzNT-D8DTjNJtqyYllu7DKo_gstP9sExe4giMKwvp3f9GiEE8EXZ4hVapoDMI46a7-koF-FRznBzo2BI01QpOw4dKqv3yo8fKJnBOmb1eAfQwQ9f4REr5KLPIGl3N7n2-lIayW7wso")',
          }}
        >
          <div className="relative z-10 max-w-2xl animate-fade-in-up">
            <h1 className="text-white text-4xl md:text-5xl lg:text-6xl font-black leading-tight tracking-tight mb-4 drop-shadow-lg">
              Handmade with love,
              <br />
              stitch by stitch.
            </h1>
            <p className="text-white/90 text-base md:text-lg lg:text-xl font-medium mb-8 max-w-lg shadow-black drop-shadow-md">
              Discover cozy crochet toys, bespoke sweaters, and patterns made
              for warmth and comfort in every season.
            </p>
            <button className="inline-flex h-12 md:h-14 items-center justify-center rounded-full bg-primary px-8 text-base font-bold text-white shadow-lg transition-transform hover:scale-105 hover:bg-primary/90 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-primary focus-visible:ring-offset-2">
              Shop Collection
            </button>
          </div>
        </div>
      </div>
    </div>
  );
};

export default Hero;

// libs/features/vue/religion-community/ui/Hero.vue
<template>
  <section class="relative w-full h-[600px] flex items-center justify-center overflow-hidden">
    <div class="absolute inset-0 z-0">
      <div class="absolute inset-0 bg-black/40 z-10"></div>
      <img alt="Community gathering" class="w-full h-full object-cover" src="https://lh3.googleusercontent.com/aida-public/AB6AXuD_RRvjazX3j1c8d-EC4bfBb21aXwv4oGLdzc1UQvbgzVR9uGPuttXUnpG9kWqTpMkJSYOe5ECHgMDhkqdnhqpInWOdirTAKH9sZKdLNoF6Tjxuv3uOTBfTECmTMOo-kgR20oZDywlJ9HWC0VX3dv4Ii05W7Jb_dFcaD9NMID-VBg0u4Bce5bpkXha8uBcmQRUpo0mUEM_fBSqpQwpW4MlEsigrkD9o-9V_6nJZpXO7dXdzJfUgOWir6DgaBX6YlztlcAKaOILG9tHZ"/>
    </div>
    <div class="relative z-20 text-center px-4 max-w-4xl">
      <span class="inline-block text-accent-gold font-bold tracking-[0.3em] uppercase mb-4 text-sm">Welcome Home</span>
      <h1 class="text-white text-5xl md:text-7xl font-black mb-6 leading-tight">Finding Peace, Purpose, and Fellowship</h1>
      <p class="text-white/90 text-lg md:text-xl mb-10 max-w-2xl mx-auto leading-relaxed">A modern sanctuary for seekers of truth, rooted in tradition and growing together in love.</p>
      <div class="flex flex-col sm:flex-row gap-4 justify-center">
        <button class="bg-primary text-white px-8 py-4 rounded-xl font-bold text-lg hover:translate-y-[-2px] transition-transform">Our Service Times</button>
        <button class="bg-white/10 backdrop-blur-md border border-white/30 text-white px-8 py-4 rounded-xl font-bold text-lg hover:bg-white/20 transition-all">Watch Online</button>
      </div>
    </div>
  </section>
</template>

<script setup lang="ts">
// Hero component
</script>

<style scoped></style>
